"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  background = "#dc322f"
  foreground = "#839496"
  leading_diamond = "╭─"
  style = "diamond"
  template = "{{ .UserName }}@{{ .HostName }}"
  type = "shell"

  [[blocks.segments]]
  background = "#b58900"
  foreground = "#839496"
  powerline_symbol = ""
  style = "powerline"
  template = "{{ .Path }} "
  type = "path"
    [blocks.segments.properties]
    folder_icon = "  "
    home_icon = " "
    style = "full"

  [[blocks.segments]]
  background = "#859900"
  background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}",
    "{{ if gt .Ahead 0 }}#C792EA{{ end }}",
    "{{ if gt .Behind 0 }}#C792EA{{ end }}"
  ]
  foreground = "#839496"
  powerline_symbol = ""
  style = "powerline"
  template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350>  {{ .Staging.String }}</>{{ end }} "
  type = "git"
    [blocks.segments.properties]
    branch_icon = " "
    fetch_status = true
    fetch_upstream_icon = true

  [[blocks.segments]]
  background = "#586e75"
  foreground = "#839496"
  style = "diamond"
  template = "  {{ .FormattedMs }}⠀"
  trailing_diamond = ""
  type = "executiontime"
    [blocks.segments.properties]
    style = "roundrock"
    threshold = 0

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  background = "#d33682"
  foreground = "#839496"
  leading_diamond = ""
  style = "diamond"
  template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
  type = "os"
    [blocks.segments.properties]
    linux = ""
    macos = ""
    windows = ""

  [[blocks.segments]]
  type = "text"
  style = "plain"
  background = "#dc322f"
  foreground = "#839496"
  template = "On"

  [[blocks.segments]]
  background = "#b58900"
  foreground = "#839496"
  style = "diamond"
  template = " {{ .Name }} "
  type = "shell"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#d33682"
  style = "plain"
  template = "╰─"
  type = "text"

  [[blocks.segments]]
  foreground = "#2aa198"
  foreground_templates = [ "{{ if gt .Code 0 }}#ef5350{{ end }}" ]
  style = "plain"
  template = " "
  type = "status"
    [blocks.segments.properties]
    always_enabled = true
