[colors.primary]
background = "#002b36"
foreground = "#839496"

[colors.normal]
black   = "#000000"
red     = "#dc322f"
green   = "#859900"
yellow  = "#b58900"
blue    = "#268bd2"
magenta = "#d33682"
cyan    = "#2aa198"
white   = "#586e75"

[colors.bright]
black   = "#555555"
red     = "#dc322f"
green   = "#859900"
yellow  = "#b58900"
blue    = "#268bd2"
magenta = "#d33682"
cyan    = "#2aa198"
white   = "#839496"
