#!/usr/bin/env bash

if [ -L /home/$USER/.config/dunst/dunstrc ]; then
    rm /home/$USER/.config/dunst/dunstrc 
    cp  /etc/openflexos/home/user/config/dunst/dunstrc /home/$USER/.config/dunst/dunstrc
fi

# Path to your themes.json file
THEMES_FILE="$HOME/.config/themes.json"

# Output dunstrc path
DUNST_FILE="$HOME/.config/dunst/dunstrc"

# Ensure jq is installed
if ! command -v jq &>/dev/null; then
  echo "Error: jq is required (install with: sudo pacman -S jq)"
  exit 1
fi

# Read current theme name
CURRENT_THEME=$(jq -r '.current' "$THEMES_FILE")

# Extract colors
BG=$(jq -r ".themes.\"$CURRENT_THEME\".bg" "$THEMES_FILE")
FG=$(jq -r ".themes.\"$CURRENT_THEME\".fg" "$THEMES_FILE")
COLOR1=$(jq -r ".themes.\"$CURRENT_THEME\".color1" "$THEMES_FILE")
COLOR2=$(jq -r ".themes.\"$CURRENT_THEME\".color2" "$THEMES_FILE")
COLOR3=$(jq -r ".themes.\"$CURRENT_THEME\".color3" "$THEMES_FILE")
COLOR4=$(jq -r ".themes.\"$CURRENT_THEME\".color4" "$THEMES_FILE")

# Validate
if [[ -z "$BG" || "$BG" == "null" ]]; then
  echo "Error: Could not find theme '$CURRENT_THEME'"
  exit 1
fi

# Generate dunstrc
mkdir -p "$(dirname "$DUNST_FILE")"

cat > "$DUNST_FILE" <<EOF
# Auto-generated by update-dunst-theme.sh
# Current theme: $CURRENT_THEME

[global]
    font = Monospace 10
    origin = top-center
    
    # Colors
    background = "${BG}"
    foreground = "${FG}"
    frame_color = "${COLOR1}"

    # Borders
    frame_width = 2
    separator_color = "${COLOR2}"

    # Padding and spacing
    padding = 10
    horizontal_padding = 10
    text_icon_padding = 10
    line_height = 0

    # Transparency
    transparency = 0

    # Icon settings
    icon_theme = Adwaita
    icon_position = left
    max_icon_size = 48

[urgency_low]
    background = "${BG}"
    foreground = "${FG}"
    frame_color = "${COLOR2}"

[urgency_normal]
    background = "${BG}"
    foreground = "${FG}"
    frame_color = "${COLOR3}"

[urgency_critical]
    background = "${BG}"
    foreground = "${FG}"
    frame_color = "${COLOR4}"
EOF

echo "✅ Dunst theme updated using theme '$CURRENT_THEME' → $DUNST_FILE"
echo "🔄 Restart dunst with: pkill dunst && dunst &"

