#!/usr/bin/env bash
# Reads the current theme from themes.json and generates alacritty.toml

# Path to your themes.json file
THEMES_FILE="$HOME/.config/themes.json"

# Path to output alacritty.toml
ALACRITTY_TOML="$HOME/.config/alacritty/alacritty.toml"

# Ensure jq is installed
if ! command -v jq &>/dev/null; then
  echo "Error: jq is required (install with: sudo apt install jq)"
  exit 1
fi

# Read current theme name
CURRENT_THEME=$(jq -r '.current' "$THEMES_FILE")

# Extract colors
BG=$(jq -r ".themes.\"$CURRENT_THEME\".bg" "$THEMES_FILE")
FG=$(jq -r ".themes.\"$CURRENT_THEME\".fg" "$THEMES_FILE")

# Check for missing theme
if [[ "$BG" == "null" || -z "$BG" ]]; then
  echo "Error: Theme '$CURRENT_THEME' not found in $THEMES_FILE"
  exit 1
fi

# Create alacritty.toml
cat > "$ALACRITTY_TOML" <<EOF
# Auto-generated by update_alacritty_theme.sh
# Current theme: $CURRENT_THEME

[colors.primary]
background = "$BG"
foreground = "$FG"
EOF

echo "✅ Alacritty theme updated to '$CURRENT_THEME' at: $ALACRITTY_TOML"

